name       : haskell-vector-binary-instances
version    : 0.2.4
release    : 2
source     :
    - https://hackage.haskell.org/package/vector-binary-instances-0.2.4/vector-binary-instances-0.2.4.tar.gz : 2b2f783e414dcf2e7dc34ad14264e5af83e5cd4784d5a0a64e4b4571963443f8
license    : BSD-3-Clause
component  : programming.haskell
summary    : Instances for Binary for the types defined in the vector package, making it easy to serialize vectors to and from disk.
description: |
    Instances for Binary for the types defined in the vector package, making it easy to serialize vectors to and from disk.
builddeps  :
    - haskell-cabal-install
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
