name       : haskell-vector-binary-instances
version    : 0.2.5.1
release    : 3
source     :
    - https://hackage.haskell.org/package/vector-binary-instances-0.2.5.1/vector-binary-instances-0.2.5.1.tar.gz : 3945b99f8efd319c837700b7cef5163ee23e656e89227357e0b7a41d2a66c512
license    : BSD-3-Clause
component  : programming.haskell
summary    : Instances for Binary for the types defined in the vector package, making it easy to serialize vectors to and from disk.
description: |
    Instances for Binary for the types defined in the vector package, making it easy to serialize vectors to and from disk.
builddeps  :
    - haskell-cabal-install
    - haskell-vector-devel
rundeps    :
    - devel:
        - haskell-vector-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
