name       : haskell-vector-binary-instances
version    : 0.2.3.4
release    : 1
source     :
    - http://hackage.haskell.org/package/vector-binary-instances-0.2.3.4/vector-binary-instances-0.2.3.4.tar.gz : f3cef04ff645bbf25198c2c0c33d0c13e44bfe63602e1e694c2be9abf0e57d00
license    : BSD-3-Clause
component  : programming.haskell
summary    : Instances for Binary for the types defined in the vector package, making it easy to serialize vectors to and from disk.
description: |
    Instances for Binary for the types defined in the vector package, making it easy to serialize vectors to and from disk.
builddeps  :
    - haskell-cabal-install
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
